exclude: '^$'
fail_fast: false
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v1.2.3'
  hooks:
  - id: check-merge-conflict

# Python formatting
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python
- repo: https://github.com/pre-commit/mirrors-isort
  rev: master
  hooks:
  - id: isort
